title: xyfancy's Blog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" 
url: "https://xyfancy.github.io/" 

# Author Settings
author: xyfancy # add your name
author-img: head.jpeg # add your photo
about-author: 东南大学计算机系统结构方向研究生. # add description
social-github: xyfancy 
social-email: yanxseu@outlook.com

# Disqus
discus-identifier: mr-brown

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
